# SPDX-FileCopyrightText: 2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0
version = 1

[[annotations]]
path = [
     "assets/assets/*.txt",
     "assets/assets/images/*.svg",
     "assets/package-lock.json",
     "assets/package.json",
     "docs/*md",
     "flake.lock",
     "go.sum",
     "handlers/examples/*.nix",
     "handlers/latex/document.tex",
     "handlers/playground/*.html",
     "handlers/playground/examples/*.nix",
     "pkg/handler/*.nix",
     "README.md",
     ".renovaterc.json"
]
precedence = "override"
SPDX-FileCopyrightText = "2025 Steffen Vogel <post@steffenvogel.de>"
SPDX-License-Identifier = "Apache-2.0"