# SPDX-FileCopyrightText: 2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

name: Build and Test

on:
  pull_request:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: stv0g/nixpresso

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: nixpresso
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build Nixpresso
      run: nix build --print-build-logs .#nixpresso

    - name: Build assets
      run: nix build --print-build-logs .#nixpresso.assets

    - name: Build docs
      run: nix build --print-build-logs .#nixpresso.docs

    - name: Test
      run: nix flake check --print-build-logs .

    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker image
      id: push
      env:
        IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      run: |
        nix build --print-build-logs .#nixpresso-docker
        ./result | docker load
        docker tag nixpresso:latest $IMAGE
        docker push $IMAGE
        IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE)
        echo "digest=${IMAGE_DIGEST#*@}" >> $GITHUB_OUTPUT

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true