# SPDX-FileCopyrightText: 2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

name: Build and Test

on:
  pull_request:
  push:
    branches:
    - main

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: stv0g/nixpresso

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: stv0g
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Build Nixpresso
      run: nix build --print-build-logs .#nixpresso

    - name: Build assets
      run: nix build --print-build-logs .#nixpresso.assets

    - name: Build docs
      run: nix build --print-build-logs .#nixpresso.docs

    - name: Test
      run: nix flake check --print-build-logs .

  docker:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: stv0g
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Log in to the Container registry
      uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker image
      env:
        IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      run: |
        nix build --print-build-logs .#nixpresso-docker
        ./result | docker load

    - name: Push Docker image
      if: github.ref == 'refs/heads/main'
      id: push
      env:
        IMAGE: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
      run: |
        docker tag nixpresso:latest $IMAGE
        docker push $IMAGE
        IMAGE_DIGEST=$(docker inspect --format='{{index .RepoDigests 0}}' $IMAGE)
        echo "digest=${IMAGE_DIGEST#*@}" >> $GITHUB_OUTPUT

    - name: Generate artifact attestation
      if: github.ref == 'refs/heads/main'
      uses: actions/attest-build-provenance@v3
      with:
        subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
        subject-digest: ${{ steps.push.outputs.digest }}
        push-to-registry: true