# SPDX-FileCopyrightText: 2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

name: Lint

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: golanci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.5.0

  deadcode:
    name: deadcode
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: stv0g
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Check for dead code
      run: nix run github:astro/deadnix


  formatting:
    name: formatting
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5

    - name: Setup Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Setup Cachix
      uses: cachix/cachix-action@v16
      with:
        name: stv0g
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Check for unformatted code
      run: nix run .#formatter.x86_64-linux -- --check **/*.nix