# SPDX-FileCopyrightText: 2025 Steffen Vogel <post@steffenvogel.de>
# SPDX-License-Identifier: Apache-2.0

name: Lint

on:
  push:
    branches:
    - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: golanci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0.2